---
run_catalogue : 
- 'event_catalogue_run00108.pkl'
    
midas_data_folder : '/work/sarthak/argset/data/'
data_folder       : '/work/chuck/sarthak/argset/event_catalogues/'
output_folder     : '/work/chuck/sarthak/argset/output_folder/'
temp_folder       : '/work/chuck/sarthak/argset/temp_folder/'